author: multitallented
database: false
description: Makes saplings and mushrooms grow into custom WorldEdit schematics
main: org.redcastlemedia.bukkit.customtrees.CustomTrees
name: CustomTrees
load: POSTWORLD
version: 2.0.0
api-version: 1.21
depend: [WorldEdit]
softdepend: [FastAsyncWorldEdit]